pipeline {
    agent any

    environment {
        AWS_REGION = "us-east-1"
        EKS_CLUSTER_NAME = "my-eks-cluster"
        DOCKER_REPO = "samqwerty12/react-app"
        ECR_REPO = "123456789012.dkr.ecr.us-east-1.amazonaws.com/react-app"
    }

    stages {

        stage('Git Checkout') {
            steps {
               git branch: 'main', credentialsId: 'github-cred', url: 'https://github.com/SamAshray1/portfolio-website.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    def DATE_TAG = new Date().format("yyyyMMdd-HH")
                    def IMAGE_TAG = "${BUILD_NUMBER}-${DATE_TAG}"

                    dockerImage = docker.build("${DOCKER_REPO}:${IMAGE_TAG}")
                }
            }
        }

        stage('Push to DockerHub') {
            steps {
                withDockerRegistry([credentialsId: 'dockerhub-credentials', url: '']) {
                    script {
                        dockerImage.push("${BUILD_NUMBER}")
                        dockerImage.push("latest")
                    }
                }
            }
        }

//        stage('Push to AWS ECR') {
//            steps {
//                script {
//                    sh """
//                        aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_REPO
//                        docker tag ${DOCKER_REPO}:${BUILD_NUMBER} $ECR_REPO:${BUILD_NUMBER}
//                        docker push $ECR_REPO:${BUILD_NUMBER}
//                    """
//                }
//            }
//        }

        stage('Provision EKS Cluster with Terraform') {
            steps {
                script {
                    sh """
                        cd terraform/
                        terraform init
                        terraform apply -auto-approve
                    """
                }
            }
        }

        stage('Configure kubectl for EKS') {
            steps {
                script {
                    sh """
                        aws eks update-kubeconfig --region $AWS_REGION --name $EKS_CLUSTER_NAME
                        kubectl get nodes
                    """
                }
            }
        }

        stage('Deploy App using Helm') {
            steps {
                script {
                    sh """
                        helm repo add my-chart-repo https://your-helm-repo
                        helm upgrade --install react-app ./helm-chart --set image.repository=$ECR_REPO,image.tag=${BUILD_NUMBER}
                    """
                }
            }
        }
    }

    post {
        always {
            cleanWs()
        }
    }
}