apiVersion: apps/v1
kind: Deployment
metadata:
  name: splunk-forwarder
spec:
  replicas: 1
  selector:
    matchLabels:
      app: splunk-forwarder
  template:
    metadata:
      labels:
        app: splunk-forwarder
    spec:
      containers:
        - name: splunk-forwarder
          image: splunk/universalforwarder:latest
          env:
            - name: SPLUNK_START_ARGS
              value: "--accept-license"
            - name: SPLUNK_USER
              value: "splunk"
          volumeMounts:
            - name: log-volume
              mountPath: /var/log/app
            - name: splunk-config
              mountPath: /opt/splunkforwarder/etc/system/local/
      volumes:
        - name: log-volume
          persistentVolumeClaim:
            claimName: log-storage-claim
        - name: splunk-config
          configMap:
            name: splunk-config
