apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-pod
spec:
  containers:
    - name: ubuntu-container
      image: ubuntu
      command: [ "sh", "-c", "tail -f /dev/null" ]  # Keeps the container alive
      volumeMounts:
        - name: log-volume
          mountPath: /var/log/app
  volumes:
    - name: log-volume
      persistentVolumeClaim:
        claimName: log-storage-claim
