# This is a sample pod yml

apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod1
  labels:
    env: demo
    type: frontend
spec:
  containers:
    - name: nginx-container
      image: nginx:latest
      ports:
      - containerPort: 80
