#   Create a new Replicaset based on the nginx image with 3 replicas
#   Update the replicas to 4 from the YAML
#   Update the replicas to 6 from the command line


apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-rs
  labels:
    app: nginx
spec:
  replicas: 4
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      name: nginx
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx-pod
          image: nginx:latest
          ports:
          - containerPort: 80



# kubectl scale --replicas=6 rs/nginx-rs
